name: Test GitHub Actions on Ubuntu, macOS, and Windows

on: [pull_request, push]

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Test with os ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v3

      - name: Replace strings in files
        uses: ./
        with:
          files: 'testfiles/test.txt,testfiles/test1.txt'
          replacements: 'SYSTEMUNDERTEST=my_system_under_test,TARGETBASEURL=https://my-target-base-url.com,ARTIFACTID=my-artifact-id'

      - name: Check if strings were replaced in file test.txt
        run: |
          if grep -q "systemUnderTest: my_system_under_test" testfiles/test.txt; then
            echo "SYSTEMUNDERTEST replaced correctly"
          else
            echo "SYSTEMUNDERTEST not replaced correctly" && exit 1
          fi
          if grep -q "targetBaseUrl: https://my-target-base-url.com" testfiles/test.txt; then
            echo "TARGETBASEURL replaced correctly"
          else
            echo "TARGETBASEURL not replaced correctly" && exit 1
          fi
      
      - name: Check if strings were replaced in file test.txt
        run: |
          if grep -q "systemUnderTest: my_system_under_test" testfiles/test1.txt; then
            echo "SYSTEMUNDERTEST replaced correctly"
          else
            echo "SYSTEMUNDERTEST not replaced correctly" && exit 1
          fi
          if grep -q "targetBaseUrl: https://my-target-base-url.com" testfiles/test1.txt; then
            echo "TARGETBASEURL replaced correctly"
          else
            echo "TARGETBASEURL not replaced correctly" && exit 1
          fi
          if grep -q "artifactId: my-artifact-id" testfiles/test1.txt; then
            echo "ARTIFACTID replaced correctly"
          else
            echo "ARTIFACTID not replaced correctly" && exit 1
          fi