name: Test GitHub Actions on Ubuntu, macOS, and Windows

on: [pull_request, push]

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Test with os ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v3

      - name: Replace strings in files
        uses: ./
        with:
          files: 'testfiles/test.txt,testfiles/test1.txt'
          replacements: 'SYSTEMUNDERTEST=my_system_under_test,TARGETBASEURL=https://my-target-base-url.com,ARTIFACTID=my-artifact-id'

      - name: Check if strings were replaced in file test.txt
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat testfiles/test.txt
          contains: |
            systemUnderTest: my_system_under_test
            targetBaseUrl: https://my-target-base-url.com      

      - name: Check if strings were replaced in file test1.txt
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat testfiles/test1.txt
          contains: |
            systemUnderTest: my_system_under_test
            targetBaseUrl: https://my-target-base-url.com
            artifactId: my-artifact-id